# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Find-Lib
version:      0.01
version_from: lib/Find/Lib.pm
installdirs:  site
requires:
    File::Spec:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
